<?php
require_once 'includes/config.php';
require_once 'includes/functions.php';
requireLogin();

$reports = getAllReports();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports - <?php echo SITE_NAME; ?></title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <?php include 'includes/navbar.php'; ?>

    <main class="container">
        <header class="page-header">
            <div>
                <h1>📄 Reports</h1>
                <p>View and manage generated reports</p>
            </div>
            <div class="page-header-actions">
                <button class="btn btn-primary" onclick="generateReport()">📊 Generate Report</button>
            </div>
        </header>

        <div class="card">
            <div class="card-header">
                <h3>All Reports</h3>
                <span class="badge badge-secondary">Generated</span>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Report Name</th>
                                <th>Type</th>
                                <th>Format</th>
                                <th>Date Range</th>
                                <th>Generated By</th>
                                <th>Status</th>
                                <th>Created</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php while ($report = mysqli_fetch_assoc($reports)): ?>
                                <tr>
                                    <td><strong><?php echo htmlspecialchars($report['report_name']); ?></strong></td>
                                    <td><span class="badge badge-info"><?php echo ucfirst($report['report_type']); ?></span></td>
                                    <td><?php echo strtoupper($report['report_format']); ?></td>
                                    <td><?php echo formatDate($report['date_from']); ?> → <?php echo formatDate($report['date_to']); ?></td>
                                    <td><?php echo htmlspecialchars($report['generated_by_name']); ?></td>
                                    <td><span class="badge badge-<?php echo getStatusBadge($report['status']); ?>"><?php echo ucfirst($report['status']); ?></span></td>
                                    <td><?php echo formatDateTime($report['created_at']); ?></td>
                                    <td>
                                        <?php if ($report['status'] === 'completed'): ?>
                                            <button class="btn btn-sm btn-success" onclick="downloadReport(<?php echo $report['id']; ?>)">Download</button>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endwhile; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>

    <script>
        function generateReport() {
            alert('Report generation dialog would appear here');
        }
        function downloadReport(id) {
            alert('Downloading report #' + id);
        }
    </script>
</body>
</html>
